#!/bin/bash

# Fungsi untuk menampilkan header berwarna
print_header() {
  tput setaf 2; tput bold
  echo "=========================================="
  echo "        USB TETHERING CONTROL MENU        "
  echo "=========================================="
  tput sgr0
}

# Fungsi untuk pause
pause() {
  echo
  read -n1 -r -p "Tekan sembarang tombol untuk kembali ke menu…" key
}

while true; do
  clear
  print_header

  echo " Pilih opsi:"
  echo "   1) USB TETHERING RESTART"
  echo "   2) USB TETHERING ON"
  echo "   3) USB TETHERING OFF"
  echo "   4) Keluar"
  echo
  read -p " Masukkan nomor [1-4]: " pilihan

  case $pilihan in
    1)
      echo
      echo -e "\e[33mMemulai Proses Restart...\e[0m"
      # Matikan tethering
      if adb shell service call tethering 3 i32 0; then
      sleep 2
      # Nyalakan tethering
      if adb shell service call tethering 3 i32 1; then
      echo -e "\e[32m✔ Proses Restart Selesai!\e[0m"
      else
      echo -e "\e[31m✘ Gagal menyalakan USB Tethering.\e[0m"
      fi
      else
      echo -e "\e[31m✘ Gagal mematikan USB Tethering.\e[0m"
      fi
      pause
      ;;
    2)
      echo
      echo -e "\e[33mMenyalakan USB Tethering...\e[0m"
      adb shell service call tethering 3 i32 1
      echo -e "\e[32m✔ USB Tethering ON\e[0m"
      pause
      ;;
    3)
      echo
      echo -e "\e[33mMematikan USB Tethering...\e[0m"
      adb shell service call tethering 3 i32 0
      echo -e "\e[31m✘ USB Tethering OFF\e[0m"
      pause
      ;;
    4)
      echo -e "\e[34mKeluar. Sampai jumpa!\e[0m"
      exit 0
      ;;
    *)
      echo -e "\e[31mPilihan tidak valid.\e[0m"
      pause
      ;;
  esac
done